version: '3.8'
services:

    backend:
        image: example-backend
        ports:
            - 127.0.0.1:8080:8080
        environment:
            - REQUEST_ORIGIN=http://localhost.
            - REDIS_HOST=redis
            - POSTGRES_HOST=postgres_db
        depends_on:
            - db
        command: ["./server"]

    frontend:
        image: example-frontend
        ports:
            - 127.0.0.1:5000:5000
        environment:
            - REACT_APP_BACKEND_URL=http://localhost/api/
        command: ["serve","-s","-l","5000","build"]

    proxy:
        image: nginx:latest
        volumes:
            - type: bind
              source: ./nginx.conf
              target: /etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on:
            - backend
            - frontend

    redis:
        image: redis
        container_name: redis
        command: ["redis-server"]

    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: postgres
        container_name: postgres_db
        volumes:
            - type: bind
              source: ./database
              target: /var/lib/postgresql/data

volumes:
    database:
