version: '3.8'
services:
    backend:
        image: example-backend
        ports:
            - 8080:8080
        environment:
            - REQUEST_ORIGIN=http://localhost:5000
            - REDIS_HOST=redis
        command: ["./server"]
    frontend:
        image: example-frontend
        ports:
            - 5000:5000
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:8080
        command: ["serve","-s","-l","5000","build"]
    redis:
        image: redis
        container_name: redis
        command: ["redis-server"]
